### PR TITLE
Fix #631

### LINKED ISSUE #631: Issue on PlayerListener class
I'm almost sure this line is wrong:

https://github.com/APDevTeam/Movecraft/blob/774013ace90033f404e02d7e29d45aa8475bbb26/modules/Movecraft/src/main/java/net/countercraft/movecraft/listener/PlayerListener.java#L107

This check is always true since `e` is an Event and well, events are never a `Player`. Also, I think this methods wants to listen for `PlayerDeathEvent` and not `EntityDamageByEntityEvent` given its name (`onPlayerDeath`).

### PR DESCRIPTION
**Pull request by Intybyte**
### Describe in detail what your pull request accomplishes
Fix an issue.
Added a config line that defaults to false for the new behaviour of releasing the craft on death.

### Related issues:
- Fix #631

### Checklist
- [ ] Tested

### CODE REVIEW

**Review by TylerS1066 — APPROVED** [review]

File: Movecraft/src/main/java/net/countercraft/movecraft/listener/PlayerListener.java [hunk 1]
```diff
@@ -102,12 +99,13 @@ public void onPlayerLogout(PlayerQuitEvent e) {
...
-    public void onPlayerDeath(EntityDamageByEntityEvent e) {
+    public void onPlayerDeath(PlayerDeathEvent e) {
         // changed to death so when you shoot up an airship and hit the pilot, it still sinks
-        if (!(e instanceof Player))
+
+        if (!Settings.ReleaseOnDeath)
             return;
 
-        Player p = (Player) e;
+        Player p = e.getPlayer();
```
Comment (TylerS1066) [inline Movecraft/src/main/java/net/countercraft/movecraft/listener/PlayerListener.java:108]: I'm not sure if this is the intent, but it only releases the craft and does not sink it.  Based on the comment I think it should sink and not release.

Comment (Intybyte) [reply Movecraft/src/main/java/net/countercraft/movecraft/listener/PlayerListener.java:108]: Not sure what would be the best behaviour in this case, releasing the craft or sink it?

Comment (TylerS1066) [reply Movecraft/src/main/java/net/countercraft/movecraft/listener/PlayerListener.java:108]: Based on the comment, I think sinking is best.  It also will mean that ships will sink, and not be left in air when the player dies.
