### PR TITLE
Fix hovering when over the void

### LINKED ISSUE #497: useGravity crafts lag when above void
**Describe the bug**
When you pilot (or move) the any craft that uses gravity above the void, the server rapidly loses tps so much so that it kicks all players. I've only seen this so far with my only land vehicle on my server, but I believe it is any craft that has the useGravity variable set in their craft configs as well. 

**To Reproduce**
1. Create a craft that uses gravity i.g. car
2. Pilot the craft above a void
3. Try to move the craft
4. Interact with the server to realize the server has a massive tps spike that it kicks you.

**Expected behavior**
UseGravity crafts over void at least shouldn't cause mass amounts of lag. 

**Versions:**
 - Movecraft: 8 a6
 - Java 16
 - Minecraft 1.16.5

### PR DESCRIPTION
**Pull request by galacticwarrior9**
### Describe in detail what your pull request accomplishes

If a craft has hover enabled but its midpoint is over the void, the ground Y check loops forever as void air is included in `Material#isAir`. This PR terminates the loop when the minimum height limit of the world is reached. 

### Related issues:
Fixes #497

### Checklist
- [x] Tested

### CODE REVIEW

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/async/translation/TranslationTask.java [hunk 1]
```diff
@@ -192,7 +193,8 @@ protected void execute() throws InterruptedException, ExecutionException {
                 int centreMinY = oldHitBox.getMinYAt(midPoint.getX(), midPoint.getZ());
                 int groundY = centreMinY;
                 World w = craft.getWorld();
-                while (w.getBlockAt(midPoint.getX(), groundY - 1, midPoint.getZ()).getType().isAir() || craft.getType().getMaterialSetProperty(CraftType.PASSTHROUGH_BLOCKS).contains(w.getBlockAt(midPoint.getX(), groundY - 1, midPoint.getZ()).getType())){
+                int minimumHeight = WorldUtils.getWorldMinHeightLimit(w);
```
Comment (TylerS1066) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/async/translation/TranslationTask.java:196]: Since this is not reused, it can be inlined in the next statement.

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/async/translation/TranslationTask.java [hunk 2]
```diff
@@ -192,7 +193,8 @@ protected void execute() throws InterruptedException, ExecutionException {
...
+                while (groundY - 1 >= minimumHeight && w.getBlockAt(midPoint.getX(), groundY - 1, midPoint.getZ()).getType().isAir() || craft.getType().getMaterialSetProperty(CraftType.PASSTHROUGH_BLOCKS).contains(w.getBlockAt(midPoint.getX(), groundY - 1, midPoint.getZ()).getType())){
```
Comment (TylerS1066) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/async/translation/TranslationTask.java:197]: While we don't have an explicit line length maximum, the condition in this while loop should be split across multiple lines to improve readability.  For example:
```java
while (groundY - 1 >= minimumHeight
        && w.getBlockAt(midPoint.getX(), groundY - 1, midPoint.getZ()).getType().isAir()
        || craft.getType().getMaterialSetProperty(CraftType.PASSTHROUGH_BLOCKS).contains(w.getBlockAt(midPoint.getX(), groundY - 1, midPoint.getZ()).getType())) {
    groundY--;
}
```

Comment (TylerS1066) [reply modules/Movecraft/src/main/java/net/countercraft/movecraft/async/translation/TranslationTask.java:197]: This clarification shows a clear problem, your statement is of the following form `a && b || c`, which will evaluate the AND before the OR (`(a && b) || c`), rather than what I suspect the intention was to be `a && (b || c)`.  Either way the intention is, you should add clarifying parenthesis such that somebody without intimate knowledge of operator precedence in java can understand the condition.

**Review by TylerS1066 — CHANGES_REQUESTED** [review]

**Comment by galacticwarrior9** [comment]
changes made

**Review by TylerS1066 — APPROVED** [review]
