### PR TITLE
Contacts fix

### LINKED ISSUE #225: /contacts shows "no contacts within range" when contacts are within range
**Describe the bug**
When crafts piloted by two different players make contact with  each other, the player that makes contact with the other craft is alerted. However, when doing /contacts, the contact craft will not show, even when both are within contact distance and within visual contact

**To Reproduce**
1. Pilot a craft
2. Let another player pilot another craft about 200 blocks from you. Both crafts must have detectionMultiplier set to  a value larger than 0
3. run /contacts
4. Notice that the other craft is not even showing

**Expected behavior**
Contacts should show on /contacts when within range of the craft's detection range.

**Screenshots**

**Versions (please complete the following information):**
 - Movecraft: [e.g. 7.0.0 recent source code]
 - Java [e.g. JDK 8.0.1]
 - Minecraft [e.g. 1.12.2]

**Additional context**
If the other player's craft is within 200 blocks at the time of piloting, it will show in /contacts. When moving out of 200 blocks range, the craft disappear from /contacts. When moving bck into that range again, it will sometimes never reappear on /contacts

### PR DESCRIPTION
**Pull request by eirikh1996**
### Describe in detail what your pull request acomplishes
In this pull request, the following is accomplished:
- Calculation of distance between two MovecraftLocations though an internal method
- Fixed an issue where /contacts would show no contacts, even when a craft was in contact with other crafts
- Simplified contact code

### Related issues:
- fixes #225

### Checklist
- [x] Unit tests 
- [x] Proper internationalization
- [x] Compiled/tested

### CODE REVIEW

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftLocation.java [hunk 1]
```diff
@@ -80,6 +80,20 @@ public MovecraftLocation subtract(MovecraftLocation l) {
...
     }
 
+    /**
+     *
+     * Gives the distance between this MovecraftLocation and another MovecraftLocation
+     *
+     * @param other the MovecraftLocation distant from this one
+     * @return the distance between this and the other MovecraftLocation
+     */
+    public int distance(MovecraftLocation other) {
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftLocation.java]: This is distance squared not, distance

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftLocation.java [hunk 2]
```diff
@@ -80,6 +80,20 @@ public MovecraftLocation subtract(MovecraftLocation l) {
         return new MovecraftLocation(getX() - l.getX(), getY() - l.getY(), getZ() - l.getZ());
     }
 
+    /**
+     *
+     * Gives the distance between this MovecraftLocation and another MovecraftLocation
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftLocation.java]: Clarify that this is euclidean distance

**Comment by eirikh1996** [comment]
Requested changes made @cccm5
