### PR TITLE
Subcraft validation

### LINKED ISSUE #410: "mustBeSubcraft" Won't Prevent Crafts from being piloted regardless of true or false setting
**Describe the bug**
Crafts, notably in my case torpedo style ones, with "mustBeSubcraft" set to true can still be launched without a parent craft.

**To Reproduce**
1. When using "LaunchTorpedo" place down a torpedo without a craft to launch from
2. Launch the torpedo
3. No warning will be shown saying that it must be part of a parent craft to launch
4. Torpedo launches without needing a parent craft

**Expected behavior**
Torpedo when not part of a piloted craft will fail to pilot/launch.

**Screenshots**
Torpedo launching without a craft to launch from

**Versions (please complete the following information):**
 - Movecraft: 8.0.0-a.2
 - Java 11 - OpenJ9
 - Minecraft e.g. 1.16.5

**Additional context**
```name: LaunchTorpedo
maxSize: 7
minSize: 2
allowedBlocks: 
    - COAL_BLOCK

forbiddenBlocks:
    - BEDROCK

canCruise: true
cruiseOnPilot: true
focusedExplosion: true
mustBeSubcraft: true
cruiseSkipBlocks: 1
cruiseSpeed: 6.5
canFly: false
minHeightLimit: 65
maxHeightLimit: 65
detectionMultiplier: 75.0
underwaterDetectionMultiplier: 4.0
collisionExplosion: 1.5
explodeOnCrash: 1.0
moveEntities: false
speed: 5.0
tryNudge: false
sinkPercent: 99.0
overallSinkPercent: 99.0
passthroughBlocks:
    - kelp
    - kelp_plant
    - tall_seagrass
    - seagrass
    - bubble_column
    - cave_air
flyblocks:
    COAL_BLOCK:
        - 10.0
        - 100.0```

### PR DESCRIPTION
**Pull request by drfiveminusmint**
### Describe in detail what your pull request acomplishes
This PR implements validation for the mustBeSubcraft flag.

### Related issues:
- Fix #410 

### Checklist
- [x] Proper internationalization
- [x] Compiled/tested

### CODE REVIEW

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+        return WorldManager.INSTANCE.executeMain(new Supplier<Result>() {
+            @Override
+            public Result get() {
+                Craft otherCraft = CraftManager.getInstance().fastNearestCraftToLoc(movecraftLocation.toBukkit(Bukkit.getWorld(world.getWorldUUID())));
+                if (otherCraft == null) {
+                    return Result.failWithMessage(I18nSupport.getInternationalisedString("Detection - Must Be Subcraft"));
+                }
+                return (otherCraft.getHitBox().contains(movecraftLocation) ? Result.succeed() : Result.failWithMessage(I18nSupport.getInternationalisedString("Detection - Must Be Subcraft")));
+            }
+        });
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java:37]: Supplier is a [`FunctionalInterface`](https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html), and thus can be supplanted by a lambda expression, however when using `executeMain` we should consider why it is done. Anything that calls the method becomes a critical path in the threading model for the plugin, so we should avoid it when possible. In this case, its because `fastNearestCraftToLoc` is being invoked, which warns the user about the thread safety of its execution context - however in reality it is perfectly safe. The issue arises because of an internal call to `Craft::getWorld`, which could be replaced by `Craft::getMovecraftWorld`, thus allowing us to run this validator fully off thread. If you'd like you can try to fix this or you can wait on me to do so.

File: modules/Movecraft/src/main/resources/localisation/movecraftlang_en.properties [hunk 2]
```diff
@@ -51,6 +51,7 @@ Detection\ -\ Not\ Registered\ Pilot=Not one of the registered pilots on this cr
 Detection\ -\ Craft\ Type\ Cannot\ Be\ Named=Crafts of this type cannot be named
 Detection\ -\ ERROR\:\ Double\ chest\ found=Detection failed\! ERROR \: Double chest found
 Detection\ -\ Failed\ -\ Water\ contact\ required\ but\ not\ found=Detection failed\: Water contact required but not found
+Detection\ -\ Must\ Be\ Subcraft=Craft\ must\ be\ part\ of\ another\ craft
```
Comment (cccm5) [inline modules/Movecraft/src/main/resources/localisation/movecraftlang_en.properties:54]: We should review the non-uniform nature of detection warning, but this is fine for now

**Comment by drfiveminusmint** [comment]
Requested changes made @cccm5

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+        if (!type.getMustBeSubcraft()) {
+            return Result.succeed();
+        }
+        IMovecraftWorld iMovecraftWorld;
+        try {
+            iMovecraftWorld = (IMovecraftWorld) world;
+        } catch (ClassCastException e) {
+            e.printStackTrace();
+            return Result.failWithMessage(ChatUtils.ERROR_PREFIX+ " An invalid world was passed to a validator!");
+        }
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java:29]: You shouldn't use a try catch here, but rather an `instanceof` expression. Furthermore, why are you even casting to the concrete class? You're not using it anywhere.

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+            //this code is copied from CraftManager.FastNearestCraftToLoc
+            if(otherCraft.getHitBox().isEmpty())
+                continue;
+            int midX = (otherCraft.getHitBox().getMaxX() + otherCraft.getHitBox().getMinX()) >> 1;
+            int midZ = (otherCraft.getHitBox().getMaxZ() + otherCraft.getHitBox().getMinZ()) >> 1;
+            long distSquared = (long) (Math.pow(midX -  movecraftLocation.getX(), 2) + Math.pow(midZ - movecraftLocation.getZ(), 2));
+            if (distSquared < closestDistSquared) {
+                closestDistSquared = distSquared;
+                foundCraft = otherCraft;
+            }
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java:45]: This is unnecessary, as in the end all you do with the closest hitbox is check if `movecraftLocation` is contained in it. Instead, you can just do that here.

**Review by cccm5 — CHANGES_REQUESTED** [review]

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java (hunk 3 above)
Comment (drfiveminusmint) [reply modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java:29]: The concrete class is necessary here because I use ``IMovecraftWorld.equals()`` which is not defined for the abstract class.

Comment (cccm5) [reply modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java:29]: all objects implement equals, notice how you never use `iMovecraftWorld` and your code still functions

Comment (drfiveminusmint) [reply modules/Movecraft/src/main/java/net/countercraft/movecraft/processing/tasks/detection/SubcraftValidator.java:29]: wait, i just noticed this :woman_facepalming: my apologies

**Comment by drfiveminusmint** [comment]
Requested changes made (again)

**Review by cccm5 — APPROVED** [review]
