### PR TITLE
Siege fixes

### LINKED ISSUE #7: Siege payment broken
after paying out to the first player, siege payments cause an npe.

### LINKED ISSUE #118: Siege duration display
**Describe the bug**
The display is in hundreds of seconds, not minutes

**To Reproduce**
1. /siege info [region]

**Expected behavior**
Display to be in minutes:seconds not hundredsOfSeconds:seconds

**Versions (please complete the following information):**
 - Movecraft: 7.0.0 prerelease 8
 - Minecraft: 1.10.2

### LINKED ISSUE #119: Siege schedule
**Describe the bug**
The time is not during the Siege schedule.

**To Reproduce**
1. /siege begin [region]

**Expected behavior**
***SIEGE OF REGION HAS BEGUN***

**Versions (please complete the following information):**
 - Movecraft: 7.0.0 prerelease 8
 - Minecraft: 1.10.2

### LINKED ISSUE #122: Siege starting requirements
I'd like the requirements of siege starting to be the same as ending (ship in box).

### PR DESCRIPTION
**Pull request by TylerS1066**
This will fix #118, fix #119, fix #122, fix #7

### CODE REVIEW

**Comment by TylerS1066** [comment]
This will fix #118, #119, #120, #122

**Comment by TylerS1066** [comment]
#118 should be fixed in https://github.com/APDevTeam/Movecraft/pull/121/commits/2bee3524a47de1393bd0706000668f7f5c2286d6

**Comment by TylerS1066** [comment]
#122 should be fixed in https://github.com/APDevTeam/Movecraft/pull/121/commits/a7ad34c5b6c2e370c92a71bb148ac56318ec7fd0

**Comment by TylerS1066** [comment]
#118 was fixed in https://github.com/APDevTeam/Movecraft/pull/121/commits/7435b546052f5625795f547d20a97f52ef826522

**Comment by TylerS1066** [comment]
@cccm5 ready for review!

**Comment by TylerS1066** [comment]
This will also fix #7 (please don't close until I confirm it does).

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/commands/SiegeCommand.java [hunk 1]
```diff
@@ -83,9 +84,9 @@ private boolean infoCommand(CommandSender commandSender, String[] args){
...
         commandSender.sendMessage("Daily income: " + ChatColor.RED + currencyFormat.format(siege.getDailyIncome()));
         commandSender.sendMessage("Day of week: " + ChatColor.RED + dayToString(siege.getDayOfWeek()));
-        commandSender.sendMessage("Start time: " + ChatColor.RED + String.format("%02d", siege.getStartTime()/100) + ":" + String.format("%02d", siege.getStartTime()%100) + " UTC");
-        commandSender.sendMessage("End time: " + ChatColor.RED + String.format("%02d", siege.getScheduleEnd()/100) + ":" + String.format("%02d",siege.getScheduleEnd()%100) + " UTC");
-        commandSender.sendMessage("Duration: " + ChatColor.RED + String.format("%02d", siege.getDuration()/100) + ":" + String.format("%02d", siege.getDuration()%100));
+        commandSender.sendMessage("Start time: " + ChatColor.RED + militaryTimeIntToString(siege.getScheduleStart()) + " UTC");
+        commandSender.sendMessage("End time: " + ChatColor.RED + militaryTimeIntToString(siege.getScheduleEnd()) + " UTC");
+        commandSender.sendMessage("Duration: " + ChatColor.RED + secondsIntToString(siege.getDuration()%60));
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/commands/SiegeCommand.java]: Why are you taking the remainder here?

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/commands/SiegeCommand.java [hunk 2]
```diff
@@ -166,6 +168,30 @@ private boolean beginCommand(CommandSender commandSender){
...
             return true;
         }
+
+        //check if piloting craft in siege region
+        Craft siegeCraft = CraftManager.getInstance().getCraftByPlayer(player);
+        if(siegeCraft == null) {
+            player.sendMessage(MOVECRAFT_COMMAND_PREFIX + I18nSupport.getInternationalisedString("You must be piloting a craft!"));
+            return true;
+        }
+        else {
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/commands/SiegeCommand.java]: unnecessary else

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/commands/SiegeCommand.java [hunk 3]
```diff
@@ -166,6 +168,30 @@ private boolean beginCommand(CommandSender commandSender){
...
+            if(!siege.getCraftsToWin().contains(siegeCraft.getType().getCraftName())) {
+                player.sendMessage(MOVECRAFT_COMMAND_PREFIX + I18nSupport.getInternationalisedString("You must be piloting a craft that can siege!"));
+                return true;
+            }
+
+            HashHitBox hitBox = siegeCraft.getHitBox();
+            int midX = (hitBox.getMaxX() + hitBox.getMinX()) / 2;
+            int midY = (hitBox.getMaxY() + hitBox.getMinY()) / 2;
+            int midZ = (hitBox.getMaxZ() + hitBox.getMinZ()) / 2;
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/commands/SiegeCommand.java]: use `HitBox::getMidPoint`

Comment (TylerS1066) [reply modules/Movecraft/src/main/java/net/countercraft/movecraft/commands/SiegeCommand.java]: I was copying from the other siege code, I'll fix both places!

**Comment by TylerS1066** [comment]
I think that is polished enough for theory, time to test and ask for a final review from @cccm5 .

**Comment by TylerS1066** [comment]
Payments still are broken.  I'll be looking into solutions as soon as possible.

**Comment by TylerS1066** [comment]
@cccm5 apologies for asking for this twice, but I'd like a final review of everything.

All bugs are fixed, new features implemented (multiple days for the siege openings and color coded info command), and some code cleanup.

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/warfare/siege/SiegePaymentTask.java [hunk 4]
```diff
@@ -19,24 +20,40 @@ public void run() {
...
+                        payRegion(tRegion);
+                        return;
                     }
                 }
             }
         }
     }
+
+    private void payRegion(ProtectedRegion region) {
+        ArrayList<OfflinePlayer> owners = new ArrayList<>();
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/warfare/siege/SiegePaymentTask.java]: Use a set or some other structure to avoid adding duplicate UUID's in the next two loops

**Comment by TylerS1066** [comment]
Requested changes made @cccm5

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/warfare/siege/Siege.java [hunk 5]
```diff
@@ -7,25 +7,31 @@
 import java.util.concurrent.atomic.AtomicReference;
 
 public class Siege {
-    @NotNull
+    @NotNull private final List<Integer> daysOfWeek;
     private final List<String> craftsToWin, commandsOnStart, commandsOnLose, commandsOnWin;
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/warfare/siege/Siege.java]: `private final List<String> craftsToWin, commandsOnStart, commandsOnLose, commandsOnWin;` still has its annotation removed.

Comment (TylerS1066) [reply modules/Movecraft/src/main/java/net/countercraft/movecraft/warfare/siege/Siege.java]: Should be fixed now.
