### PR TITLE
Repair system fix

### LINKED ISSUE #5: Repair errors
Repairing a ship can sometimes paste the repair schematic in an incorrect position. Most likely due to errors in the repair recognition code, or the ability to have multiple repair signs of the same state.

### LINKED ISSUE #71: Factory save failed, despite not having FAWE installed
I ran a self-built JAR from the APDevTeam repo. When trying to save a repair state, it fails to save and I get this warning in console:

```[16:11:08 WARN]: [Movecraft] Factory save failed, this is typically caused by FAWE
[16:11:08 WARN]: java.lang.ArrayIndexOutOfBoundsException: 62
[16:11:08 WARN]:        at com.sk89q.worldedit.CuboidClipboard.setBlock(CuboidClipboard.java:512)
[16:11:08 WARN]:        at net.countercraft.movecraft.listener.WorldEditInteractListener.WEOnPlayerInteract(WorldEditInteractListener.java:253)
[16:11:08 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:11:08 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:11:08 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:11:08 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[16:11:08 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[16:11:08 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:11:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[16:11:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[16:11:08 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
[16:11:08 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:879)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[16:11:08 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:11:08 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[16:11:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[16:11:08 WARN]:        at java.lang.Thread.run(Unknown Source)
```
It says this error is typically caused by FAWE, but I have no FAWE installed. All plugins I have installed are Movecraft and WorldEdit 6.1.9

What is causing this issue?

### PR DESCRIPTION
**Pull request by eirikh1996**
A fixed repair system that puts blocks in the correct place, is not plagued with exceptions, and can even repair beds and doors

- fixes #71 
- fixes #5

### CODE REVIEW

**Comment by eirikh1996** [comment]
@cccm5 Did some improvements. Review please

**Comment by cccm5** [comment]
This needs to pass compilation tests before I review

**Comment by eirikh1996** [comment]
@cccm5 Made some fixes now. You can review

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/repair/RepairUtils.java [hunk 1]
```diff
@@ -0,0 +1,4 @@
+package net.countercraft.movecraft.repair;
+
+public class RepairUtils {
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/repair/RepairUtils.java]: This is empty

**Comment by eirikh1996** [comment]
@cccm5 review requested

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/Movecraft.java [hunk 2]
```diff
@@ -379,7 +381,19 @@ public void onEnable() {
 
             getServer().getPluginManager().registerEvents(new InteractListener(), this);
             if (worldEditPlugin != null) {
-                getServer().getPluginManager().registerEvents(new WorldEditInteractListener(), this);
+                final Class clazz;
+                try {
+                    clazz = Class.forName("net.countercraft.movecraft.compat.we6.IMovecraftRepair");
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/Movecraft.java]: As far as I can tell, this is pointless and could be simplified greatly

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+public abstract class MovecraftRepair {
+    public abstract boolean saveCraftRepairState(Craft craft, Sign sign, String repairStateName);
+    public abstract boolean saveRegionRepairState(World world, ProtectedRegion region);
+    public abstract Clipboard loadCraftRepairStateClipboard(Craft craft, Sign sign, String repairStateName, World bukkitWorld);
+    public abstract Clipboard loadRegionRepairStateClipboard(String repairStateName, World bukkitWorld);
+    public abstract HashMap<Material, Double> getMissingBlocks(String repairName);
+    public abstract ArrayDeque<Pair<Vector, Vector>> getMissingBlockLocations(String repairName);
+    public abstract long getNumDiffBlocks(String repairName);
+    public abstract org.bukkit.util.Vector getDistanceFromSignToLowestPoint(Clipboard clipboard);
+    public abstract org.bukkit.util.Vector getDistance(String repairName);
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java]: This does not need to exist at the API level

File: modules/api/src/main/java/net/countercraft/movecraft/utils/Pair.java [hunk 4]
```diff
@@ -0,0 +1,54 @@
+package net.countercraft.movecraft.utils;
+
+import java.io.Serializable;
+import java.util.Map;
+import java.util.UUID;
+
+public class Pair<L,R> implements Serializable, Map.Entry<L,R>{
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/utils/Pair.java]: Do not implement your own Pair class. You've made several mistakes in this one, such as breaking the `HashCode` contract.

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java (hunk 3 above)
Comment (cccm5) [reply modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java]: For clarification, there's only one implementation of this, and it exists in its own module - there is no need for an abstract class to define it.

File: modules/api/src/main/java/net/countercraft/movecraft/config/Settings.java [hunk 5]
```diff
@@ -50,6 +50,7 @@
     public static int ManOverBoardTimeout = 60;
     public static int FireballLifespan = 6;
     public static int RepairTicksPerBlock = 0;
+    public static double RepairMaxPercent = 50;
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/config/Settings.java]: You've added a config option but not loaded it from file

File: modules/worldedit/WE6Utils/src/main/java/net/countercraft/movecraft/compat/we6/IMovecraftRepair.java [hunk 6]
```diff
@@ -0,0 +1,523 @@
...
+            Vector offset = new Vector(sign.getX() - distance.getBlockX(), sign.getY() - distance.getBlockY(), sign.getZ() - distance.getBlockZ());
+            if (distanceMap.containsKey(repairStateFile)) {
+                distanceMap.replace(repairStateFile, offset);
+            } else {
+                distanceMap.put(repairStateFile, offset);
+            }
+            for (int x = 0; x <= size.getBlockX(); x++) {
+                for (int y = 0; y <= size.getBlockY(); y++) {
+                    for (int z = 0; z <= size.getBlockZ(); z++) {
+                        com.sk89q.worldedit.Vector position = new com.sk89q.worldedit.Vector(minPos.getBlockX() + x, minPos.getBlockY() + y, minPos.getBlockZ() + z);
```
Comment (cccm5) [inline modules/worldedit/WE6Utils/src/main/java/net/countercraft/movecraft/compat/we6/IMovecraftRepair.java]: Use imports

File: modules/worldedit/WE6Utils/src/main/java/net/countercraft/movecraft/compat/we6/IMovecraftRepair.java [hunk 7]
```diff
@@ -0,0 +1,523 @@
...
+
+    private Set<BaseBlock> baseBlocksFromAssaultRegion(com.sk89q.worldedit.Vector minPos, com.sk89q.worldedit.Vector maxPos, World world) {
+        HashSet<BaseBlock> returnSet = new HashSet<>();
+        for (int x = minPos.getBlockX(); x <= maxPos.getBlockX(); x++) {
+            for (int y = minPos.getBlockY(); y <= maxPos.getBlockY(); y++) {
+                for (int z = minPos.getBlockZ(); z <= maxPos.getBlockZ(); z++) {
+                    int id = world.getBlockTypeIdAt(x, y, z);
+                    byte data = world.getBlockAt(x, y, z).getData();
+                    //exclude air and blocks that are not destroyable during an assault
+                    if (!Settings.AssaultDestroyableBlocks.contains(id) || id == 0) {
```
Comment (cccm5) [inline modules/worldedit/WE6Utils/src/main/java/net/countercraft/movecraft/compat/we6/IMovecraftRepair.java]: This settings check can be done before the loop

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/repair/Repair.java [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+        this.name = name;
+        this.craft = craft;
+        this.updateCommands = updateCommands;
+        this.fragileBlockUpdateCommands = fragileBlockUpdateCommands;
+        this.durationInTicks = missingBlocks * Settings.RepairTicksPerBlock;
+        this.ticksSinceStart = 0;
+        this.missingBlocks = missingBlocks;
+        this.playerUUID = playerUUID;
+        this.signLoc = signLoc;
+        progressBar = Bukkit.createBossBar(this.name, BarColor.WHITE, BarStyle.SOLID, BarFlag.DARKEN_SKY);
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/repair/Repair.java]: Use `this.progressBar` to follow with other code

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/Movecraft.java (hunk 2 above)
Comment (eirikh1996) [reply modules/Movecraft/src/main/java/net/countercraft/movecraft/Movecraft.java]: well, I did it like this with possible future 1.13+ compatibility in mind due to that WE 7.0.0 for 1.13+ have quite different code than WE 6.1.9 that works up to 1.12.2. This can, however, be re-implemented if 1.13+ compat is implemented here

Comment (cccm5) [reply modules/Movecraft/src/main/java/net/countercraft/movecraft/Movecraft.java]: Hm... Maybe we should implement 1.13 before continuing this pr then?

**Comment by eirikh1996** [comment]
Requested changes made @cccm5

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/listener/WorldEditInteractListener.java [hunk 9]
```diff
@@ -113,8 +92,7 @@ public boolean repairRegion(World w, String regionName) {
         return true;
     }
 
-    @EventHandler
-    public void WEOnPlayerInteract(PlayerInteractEvent event) {
+    /*public void WEOnPlayerInteract(PlayerInteractEvent event) {
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/listener/WorldEditInteractListener.java]: Delete this instead of commenting it out

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/mapUpdater/update/WorldEditUpdateCommand.java [hunk 10]
```diff
@@ -62,17 +88,66 @@ public void doUpdate() {
...
+                //first line
+                String firstLine = nbtData.getString("Text1");
+                firstLine = firstLine.substring(2);
+                if (firstLine.substring(0, 5).equalsIgnoreCase("extra")){
+                    firstLine = firstLine.substring(17);
+                    String[] parts = firstLine.split("\"");
+                    firstLine = parts[0];
+                } else {
+                    firstLine = "";
+                }
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/mapUpdater/update/WorldEditUpdateCommand.java]: If you're repeatedly doing the same thing, use a loop or a method

File: modules/worldedit/WE6Utils/src/main/java/net/countercraft/movecraft/compat/we6/IMovecraftRepair.java [hunk 11]
```diff
@@ -0,0 +1,5 @@
+package net.countercraft.movecraft.compat.we6;
+
+public class IMovecraftRepair {
```
Comment (cccm5) [inline modules/worldedit/WE6Utils/src/main/java/net/countercraft/movecraft/compat/we6/IMovecraftRepair.java]: Delete this

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java [hunk 12]
```diff
@@ -0,0 +1,473 @@
...
+                        if (block.getType() == 0) {
+                            isImportant = false;
+                        }
+
+                        if (isImportant && bukkitBlock.getTypeId() != block.getType()) {
+                            int itemToConsume = block.getType();
+                            double qtyToConsume = 1.0;
+                            numDiffBlocks++;
+                            //some blocks aren't represented by items with the same number as the block
+                            if (itemToConsume == 63 || itemToConsume == 68) // signs
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java]: Use a switch statement or use `else`

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java [hunk 13]
```diff
@@ -0,0 +1,473 @@
...
+                        Location bukkitLoc = new Location(sign.getWorld(), offset.getBlockX() + x, offset.getBlockY() + y, offset.getBlockZ() + z);
+                        //
+                        BaseBlock block = clipboard.getBlock(position);
+                        Block bukkitBlock = sign.getWorld().getBlockAt(bukkitLoc);
+                        boolean isImportant = true;
+                        if (block.getType() == 0) {
+                            isImportant = false;
+                        }
+
+                        if (isImportant && bukkitBlock.getTypeId() != block.getType()) {
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java]: `isImportant` is equivalent to `block.getType() != 0`, just use that instead

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java [hunk 14]
```diff
@@ -0,0 +1,473 @@
...
+        Clipboard clipboard;
+        HashHitBox hitBox = craft.getHitBox();
+        try {
+            clipboard = ClipboardFormat.SCHEMATIC.getReader(new FileInputStream(file)).read(worldData);
+
+        } catch (IOException e) {
+            e.printStackTrace();
+            return null;
+        }
+        if (clipboard != null) {
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java]: This if statement can be inverted

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/RepairSign.java [hunk 15]
```diff
@@ -1,6 +1,270 @@
...
+        }
+        String repairName = event.getPlayer().getName();
+        repairName += "_";
+        repairName += sign.getLine(1);
+        MovecraftRepair movecraftRepair = MovecraftRepair.getInstance();
+        Clipboard clipboard = movecraftRepair.loadCraftRepairStateClipboard(pCraft, sign, repairName, world);
+
+
+        if (clipboard == null){
+            p.sendMessage(I18nSupport.getInternationalisedString("REPAIR STATE NOT FOUND"));
```
Comment (cccm5) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/RepairSign.java]: add a `return` statement and unroll the else

**Comment by eirikh1996** [comment]
Changes made @cccm5

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java [hunk 16]
```diff
@@ -158,166 +158,187 @@ public Clipboard loadCraftRepairStateClipboard(Craft craft, Sign sign, String re
...
-                                            if (cTag.toString().contains("minecraft:water_bucket")) {
-                                                numWaterBuckets += cTag.getByte("Count");
+                            switch (itemToConsume) {
+                                case 63:// signs
+                                    itemToConsume = 323;
+                                    break;
+                                case 68:
+                                    itemToConsume = 323;
+                                    break;
+                                case 93:// repeaters
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java]: in the case that 2 keys map to the same operation, you can simply omit the `break;` statement and allow the execution to fall through

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java [hunk 17]
```diff
@@ -158,166 +158,187 @@ public Clipboard loadCraftRepairStateClipboard(Craft craft, Sign sign, String re
...
 
         } catch (IOException e) {
             e.printStackTrace();
             return null;
         }
-        if (clipboard != null) {
+        if (clipboard == null) {
+            return null;
+        }
             long numDiffBlocks = 0;
```
Comment (cccm5) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java]: Incorrect spacing

**Comment by eirikh1996** [comment]
Requested change done @cccm5

**Comment by eirikh1996** [comment]
done the last of the requested change @cccm5

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/RepairSign.java [hunk 18]
```diff
@@ -1,6 +1,265 @@
...
+            event.getPlayer().sendMessage("You must specify a repair state name on second line");
+            event.setCancelled(true);
+            return;
+        }
+    }
+
+    @EventHandler
+    public void onSignClick(PlayerInteractEvent event){
+        String firstLine = "";
+        if (event.getAction() == Action.RIGHT_CLICK_BLOCK || event.getAction() == Action.LEFT_CLICK_BLOCK) {
```
Comment (TylerS1066) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/RepairSign.java]: (opinion) It may make the most sense to return here if the action is not a right or left click, then go through the logic for each action.

Ex:
if(!right || !left)
  return

if right
  *starting repair*
else
  *saving state*

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java [hunk 19]
```diff
@@ -0,0 +1,474 @@
...
+    private HashMap<String, ArrayDeque<ImmutablePair<Vector,Vector>>> locMissingBlocksMap = new HashMap<>();
+    private HashMap<String, Long> numDiffBlocksMap = new HashMap<>();
+    private HashMap<String, HashMap<Material, Double>> missingBlocksMap = new HashMap<>();
+    private final HashMap<String, Vector> distanceMap = new HashMap<>();
+
+    public MovecraftRepair(Plugin plugin) {
+        this.plugin = plugin;
+    }
+
+    public boolean saveCraftRepairState(Craft craft, Sign sign, String s) {
```
Comment (TylerS1066) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java]: (opinion) Isn't passing the string in addition to the sign redundant?

File: modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java [hunk 20]
```diff
@@ -0,0 +1,474 @@
...
+        com.sk89q.worldedit.world.World weWorld = new BukkitWorld(world);
+        WorldData worldData = weWorld.getWorldData();
+        Vector origin = new Vector(sign.getX(),sign.getY(),sign.getZ());
+        if (!saveDirectory.exists()) {
+            saveDirectory.mkdirs();
+        }
+        Vector minPos = new Vector(hitBox.getMinX(), hitBox.getMinY(), hitBox.getMinZ());
+        Vector maxPos = new Vector(hitBox.getMaxX(), hitBox.getMaxY(), hitBox.getMaxZ());
+        CuboidRegion cRegion = new CuboidRegion(minPos, maxPos);
+        File repairStateFile = new File(saveDirectory, s + ".schematic");
```
Comment (TylerS1066) [inline modules/api/src/main/java/net/countercraft/movecraft/MovecraftRepair.java]: Are you making sure to parse the string for dangerous characters?

File: modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/RepairSign.java [hunk 21]
```diff
@@ -1,6 +1,265 @@
...
+    }
+    //
+    private void signLeftClick(PlayerInteractEvent event){
+
+        Sign sign = (Sign) event.getClickedBlock().getState();
+        if (!sign.getLine(0).equalsIgnoreCase(HEADER) || sign.getLine(0) == null){
+            return;
+        }
+        String repairName = event.getPlayer().getName();
+        repairName += "_";
```
Comment (TylerS1066) [inline modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/RepairSign.java]: Might make sense to create a function to get or save the repair schematic from a sign since it is used in both save and load (simplifies changes to either and reduces the chance of bugs in one or the other).

Comment (TylerS1066) [reply modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/RepairSign.java]: This also could allow you to parse the file name there and avoid issues with dangerous characters
